#!/usr/bin/env bash
# Install nginx on web server

apt-get update
apt-get install -y nginx
sed -i 's/^listen\s*80\s*;/listen 80;/g' /etc/nginx/sites-available/default
kill -s HUP $(cat /var/run/nginx.pid) > /dev/null 2>&1
echo "Hello World!" > /var/www/html/index.html
