#!/usr/bin/env bash
# Install the web server 'nginx' on the server

apt-get update -y
apt-get upgrade -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
