#!/usr/bin/env bash
# This script displays the name, id, and home directory of users in file

while IFS=: read -r username _ userid _ _ home _; do
    echo "$username:$userid:$home"
done < /etc/passwd
